import type { ScoutCard } from "../types.js";

/**
 * Optional LLM layer. If OPENAI_API_KEY is set, commentary + scouting reports
 * are generated by the model. If not, a strong deterministic engine runs so the
 * product is fully functional offline. This mirrors the edge-first ethos:
 * the cloud is an enhancement, never a dependency.
 */

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

export function llmEnabled(): boolean {
  return Boolean(process.env.OPENAI_API_KEY);
}

export async function chat(system: string, user: string, maxTokens = 320): Promise<string | null> {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return null;
  const model = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  try {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        temperature: 0.7,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
    });
    if (!res.ok) return null;
    const json = (await res.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    return json.choices?.[0]?.message?.content?.trim() ?? null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Commentary
// ---------------------------------------------------------------------------

export interface CommentaryRequest {
  event: "score" | "streak" | "jump" | "whistle" | "steal" | "highlight";
  team?: "A" | "B";
  teamName?: string;
  value?: number;
  scoreA?: number;
  scoreB?: number;
  style?: "playground" | "broadcast" | "hype";
}

const PHRASES: Record<string, Record<string, string[]>> = {
  playground: {
    score: ["Bucket! Get that man some water.", "Cash. Money. Splash.", "And-1 energy, put it on the board.", "Cooked him — that's a bucket."],
    streak: ["They can't miss right now!", "Somebody call timeout, this is a takeover.", "On fire — the court is theirs."],
    jump: ["Elevator's broken, kid took the stairs to the roof.", "Get up! That's air time.", "Hang time for days."],
    whistle: ["Ball's out — check it up.", "Off the line, we resetting.", "Out of bounds, other ball."],
    steal: ["Picked his pocket!", "Hands like a thief in the night.", "Takeaway and gone."],
    highlight: ["That's a poster. Frame it.", "SportsCenter top ten, easy.", "Oh, that's nasty."],
  },
  broadcast: {
    score: ["Knocks it down, and the lead grows.", "Elevates, releases — good.", "Finds the bottom of the net with confidence."],
    streak: ["An 8-0 run and the building is electric.", "They've seized all the momentum here.", "A decisive stretch of basketball."],
    jump: ["Rises up with tremendous elevation.", "Extraordinary vertical explosion on that finish.", "Skies above the defense."],
    whistle: ["The ball sails out of bounds — turnover.", "Off the mark and out — change of possession.", "Whistle. Ball did cross the line."],
    steal: ["Reads the passing lane perfectly for the steal.", "Anticipation, and a takeaway.", "Jumps the route — turnover forced."],
    highlight: ["A signature moment in this one.", "That's a play they'll be replaying tonight.", "Sensational — simply sensational."],
  },
  hype: {
    score: ["BANG! Count it!", "SPLASH from deep!", "GET UP! It's good!", "DAGGER!"],
    streak: ["THEY ARE UNCONSCIOUS RIGHT NOW!", "THE RUN IS ON! TIMEOUT!", "IT'S A TAKEOVER!"],
    jump: ["OH MY — HE TOOK OFF!", "ABOVE THE RIM! ARE YOU KIDDING?!", "THROW IT DOWN!"],
    whistle: ["OUT OF BOUNDS — CV CALLS IT INSTANTLY!", "OFF THE LINE! WE RESET!", "GONE! OTHER BALL!"],
    steal: ["THIEF! GONE THE OTHER WAY!", "PICKED CLEAN!", "TAKEAWAY — HOUSTON, WE HAVE A FASTBREAK!"],
    highlight: ["POSTERIZED! GOODNIGHT!", "TOP TEN — NUMBER ONE!", "UNREAL! UNREAL!"],
  },
};

function pick<T>(arr: T[], seed: number): T {
  return arr[Math.abs(seed) % arr.length];
}

export function deterministicCommentary(req: CommentaryRequest): string {
  const style = req.style ?? "playground";
  const bank = PHRASES[style] ?? PHRASES.playground;
  const list = bank[req.event] ?? bank.highlight;
  const seed = (req.value ?? 0) + (req.scoreA ?? 0) * 7 + (req.scoreB ?? 0) * 13 + req.event.length;
  let line = pick(list, seed);
  if (req.event === "score" && req.teamName && req.scoreA != null && req.scoreB != null) {
    line += ` ${req.teamName} — ${req.scoreA}-${req.scoreB}.`;
  }
  return line;
}

export async function generateCommentary(
  req: CommentaryRequest,
): Promise<{ text: string; source: "llm" | "engine" }> {
  if (llmEnabled()) {
    const style = req.style ?? "playground";
    const text = await chat(
      `You are a ${style} basketball commentator for Anact Ortho. Respond with ONE short, punchy line (max 14 words). No emojis unless hype style.`,
      `Event: ${req.event}. Team: ${req.teamName ?? req.team ?? "?"}. Value: ${req.value ?? "-"}. Score: ${req.scoreA ?? 0}-${req.scoreB ?? 0}.`,
      40,
    );
    if (text) return { text, source: "llm" };
  }
  return { text: deterministicCommentary(req), source: "engine" };
}

// ---------------------------------------------------------------------------
// Scouting report
// ---------------------------------------------------------------------------

export function deterministicReport(card: ScoutCard): string {
  const p = card.player;
  const fg = p.shots ? Math.round((p.makes / p.shots) * 100) : 0;
  const pos = p.position ?? "combo guard";
  const explosive = p.bestJumpCm >= 65 ? "elite" : p.bestJumpCm >= 50 ? "above-average" : "developing";
  const release = p.topReleaseMps >= 9 ? "a quick, high-velocity release" : "a compact release with room to add speed";
  const motor = p.distanceM >= 1500 ? "a relentless motor" : "efficient movement";
  const verdict =
    p.points >= 24
      ? "Projects as a primary scoring option with clear next-level upside."
      : p.points >= 14
        ? "Projects as a reliable secondary creator and connector."
        : "A role player whose value shows up in the margins.";

  return [
    `PROSPECT REPORT — ${p.name} (${pos}).`,
    `Put up ${p.points} points on ${fg}% shooting across ${card.events.length} tracked events in a ${Math.round(card.duration / 60000)}-minute session.`,
    `Athletic profile: ${explosive} explosiveness (${p.bestJumpCm.toFixed(0)}cm measured vertical) paired with ${release} (${p.topReleaseMps.toFixed(1)} m/s). Shows ${motor} (${p.distanceM.toFixed(0)}m covered).`,
    verdict,
    `All metrics captured on-device by Anact Ortho — no wearables, no manual tagging.`,
  ].join(" ");
}

export async function generateScoutingReport(
  card: ScoutCard,
): Promise<{ text: string; source: "llm" | "engine" }> {
  if (llmEnabled()) {
    const p = card.player;
    const fg = p.shots ? Math.round((p.makes / p.shots) * 100) : 0;
    const text = await chat(
      "You are an NBA-level scout writing a concise, professional prospect report (about 90-120 words). Be specific and grounded in the numbers provided. No hype clichés.",
      `Player ${p.name}, position ${p.position ?? "guard"}. Session: ${p.points} pts on ${fg}% FG, ${p.bestJumpCm.toFixed(0)}cm vertical, ${p.topReleaseMps.toFixed(1)} m/s release, ${p.distanceM.toFixed(0)}m covered, ${p.jumps} jumps, over ${Math.round(card.duration / 60000)} minutes.`,
      300,
    );
    if (text) return { text, source: "llm" };
  }
  return { text: deterministicReport(card), source: "engine" };
}
